---
deployment:
  tasks:
    - export REPO_PATH=$(pwd)
    - export DEPLOYPATH=${CPANEL_HOME:=/home/mimarcae}/public_html
    - export NODE_ENV=production
    - cd $REPO_PATH
    - npm install
    - npm run build
    - test -d $DEPLOYPATH && rm -rf $DEPLOYPATH/* || mkdir -p $DEPLOYPATH
    - cp -R dist/* $DEPLOYPATH/
    - chmod 755 $DEPLOYPATH
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - cp .htaccess $DEPLOYPATH/ 2>/dev/null || true