---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tu_usuario/public_html/
    - export NODE_ENV=production
    - /usr/local/bin/npm ci
    - /usr/local/bin/npm run build
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R dist/* $DEPLOYPATH/