---
deployment:
  tasks:
    - export REPO_PATH=$(pwd)
    - export DEPLOYPATH=${CPANEL_HOME:=/home/mimarcae}/public_html
    - cd $REPO_PATH
    - npm run build
    - rm -rf $DEPLOYPATH
    - mkdir -p $DEPLOYPATH
    - cp -R dist/. $DEPLOYPATH/
    - cp .htaccess $DEPLOYPATH/ 2>/dev/null || true
